import './element.dart';
import 'package:flutter/material.dart';

final List<TableElement> groupOne = [
  TableElement(
      "H",
      "Hydrogen",
      1,
      1,
      Color(0xFFA3C7D2),
      0.000082,
      1312.05,
      13.99,
      20.27,
      "A colourless, odourless gas.\nIt has the lowest density of all gases."),
  TableElement(
      "Li",
      "Lithium",
      3,
      7,
      Color(0xFFEBBFD8),
      0.534,
      520.22,
      453.65,
      1615.0,
      "A soft, silvery metal.\nIt has the lowest density of all metals.\nIt reacts vigorously with water."),
  TableElement(
      "Na",
      "Sodium",
      11,
      23,
      Color(0xFFEBBFD8),
      0.97,
      495.84,
      370.94,
      1156.09,
      "Sodium is a soft metal that tarnishes within seconds of being exposed to the air.\nIt also reacts vigorously with water."),
  TableElement(
    "K",
    "Potassium",
    19,
    39,
    Color(0xFFEBBFD8),
    0.89,
    418.80,
    336.7,
    1032,
    "A soft, silvery metal that tarnishes in air within minutes.",
  ),
  TableElement(
      "Rb",
      "Rubidium",
      37,
      84,
      Color(0xFFEBBFD8),
      1.53,
      403.03,
      312.45,
      961,
      "A soft metal that ignites in the air.\n It reacts violently with water."),
  TableElement(
      "Cs",
      "Caesium",
      55,
      133,
      Color(0xFFEBBFD8),
      1.873,
      375.70,
      301.7,
      944,
      "Caesium is a soft, gold-coloured metal.\nItsis quickly attacked by air and reacts explosively in water."),
  TableElement(
    "Fr",
    "Francium",
    87,
    233,
    Color(0xFFEBBFD8),
    null,
    392.96,
    294,
    923,
    "An intensely radioactive metal.",
  ),
];

// TableElement(String symbol, String name, int atomicNum, int atomicMass,
//               Color(0xFF/FBC9E5), double density, double ionizationenergy, int melting,
//               int boiling, String appearance)

final List<TableElement> groupTwo = [
  TableElement(
      "Be",
      "Beryllium",
      4,
      9,
      Color(0xFFFBC9E5),
      1.85,
      899.50,
      1560.0,
      2741.0,
      " Beryllium is a silvery-white metal.\nIt is relatively soft and has a low density."),
  TableElement(
      "Mg",
      "Magnesium",
      12,
      24,
      Color(0xFFFBC9E5),
      1.74,
      737.35,
      923.0,
      1363.0,
      " A silvery-white metal that ignites easily\nin air and burns with a bright light."),
  TableElement(
      "Ca",
      "Calcium",
      20,
      40,
      Color(0xFFFBC9E5),
      1.54,
      389.83,
      1115.0,
      1757.0,
      " Calcium is a silvery-white, soft metal.\n It tarnishes rapidly in air and reacts with water."),
  TableElement(
      "Sr",
      "Strontium",
      38,
      88,
      Color(0xFFFBC9E5),
      2.64,
      549.47,
      1050.0,
      1650.0,
      " A soft, silvery metal that burns in air and reacts with water."),
  TableElement(
      "Ba",
      "Barium",
      56,
      137,
      Color(0xFFFBC9E5),
      3.62,
      502.84,
      1000.0,
      2118.0,
      " Barium is a soft, silvery metal.\nIt rapidly tarnishes in air and reacts with water."),
  TableElement(
    "Ra",
    "Radium",
    88,
    236,
    Color(0xFFFBC9E5),
    5.00,
    509.29,
    969.0,
    1773.0,
    " A soft, shiny and silvery radioactive metal.",
  ),
];
